export interface GlossaryTerm {
  slug: string
  term: string
  reading?: string
  oneLiner: string
  explanation: string
  example: string
  useCase: string
  relatedTerms: string[]
  lessonNumbers: number[]
}

export const glossaryTerms: GlossaryTerm[] = [
  {
    slug: 'voltage',
    term: '電圧',
    reading: 'でんあつ',
    oneLiner: '電気を押す力',
    explanation: '電圧は、電気を流そうとする「押し」の力です。水道にたとえると、タンクの高さや水圧のようなものです。電池やコンセントには電圧があり、＋側が高く、−側が低くなっています。この高低差（電位差）があるから電流が流れます。電圧が高いほど、同じ抵抗でも多くの電流を流せます。',
    example: '乾電池は1.5V、家庭のコンセントは100V、USBは5V、自動車のバッテリーは12Vの電圧があります。',
    useCase: '回路を設計するとき、部品に適切な電圧を供給するために使います。電圧が高すぎると部品が壊れ、低すぎると動きません。センサーやLEDには「動作電圧」があり、それに合わせて電源を選びます。',
    relatedTerms: ['電流', '抵抗', '回路', '電池', 'オームの法則'],
    lessonNumbers: [1, 7, 10],
  },
  {
    slug: 'current',
    term: '電流',
    reading: 'でんりゅう',
    oneLiner: '電気の流れる量',
    explanation: '電流は、回路の中を流れる電気の量です。水道にたとえると、パイプの中を流れる水の量のようなものです。電流が多いほど、LEDは明るく光り、モーターは強く回ります。電流の単位はアンペア（A）で、小さな電流はミリアンペア（mA）で表します。',
    example: 'LEDには約10〜20mA、小型モーターには数百mA、スマホの充電には1〜2A、エアコンには10A以上の電流が流れます。',
    useCase: '部品を動かすのに必要な電流を知り、電源や配線を選ぶために使います。部品には流せる電流の限界があり、超えると壊れてしまいます。',
    relatedTerms: ['電圧', '抵抗', '回路', 'アンペア', 'オームの法則'],
    lessonNumbers: [1, 7, 8, 10],
  },
  {
    slug: 'resistance',
    term: '抵抗',
    reading: 'ていこう',
    oneLiner: '電気の流れにくさ',
    explanation: '抵抗は、電流の流れを妨げる性質です。水道にたとえると、パイプが細いほど水が流れにくくなるのと同じです。抵抗器という部品を使って、電流の量を調整できます。抵抗の単位はオーム（Ω）で、数字が大きいほど電流が流れにくくなります。',
    example: 'LEDに330Ωの抵抗をつなぐと、電流を適切な量に制限できます。よく使う値は100Ω、330Ω、1kΩ、10kΩなどです。',
    useCase: 'LEDを守ったり、センサーの信号を調整したり、電流を制御するために使います。電流を制限する「ブレーキ」の役割をします。',
    relatedTerms: ['電圧', '電流', '回路', 'オーム', 'オームの法則'],
    lessonNumbers: [1, 7, 8, 9, 10],
  },
  {
    slug: 'sensor',
    term: 'センサー',
    reading: 'せんさー',
    oneLiner: '世界を測る部品',
    explanation: 'センサーは、温度・光・音・距離など、周りの物理量を電気信号に変える部品です。人間の五感（目・耳・肌など）のように、コンピュータに「世界の情報」を伝えます。センサーがあるから、コンピュータは外の世界を知ることができます。',
    example: '温度センサー、光センサー、距離センサー、ボタン（押されたかどうかを知る）、加速度センサーなどがあります。',
    useCase: '自動ドア、スマートフォン、工場の監視システムなど、あらゆる自動化に使います。「温度が高くなったら通知」「人が来たら点灯」など、入力の起点になります。',
    relatedTerms: ['入力', 'マイコン', 'GPIO', '物理量'],
    lessonNumbers: [4, 5, 31, 32, 33],
  },
  {
    slug: 'microcontroller',
    term: 'マイコン',
    oneLiner: '小さなコンピュータ',
    explanation: 'マイコン（マイクロコントローラ）は、1つのチップに入った小さなコンピュータです。センサーからの信号を受け取り、プログラムで判断し、モーターやLEDを動かせます。',
    example: 'Arduino、ESP32、M5Stackなどがマイコンを使った製品です。',
    useCase: '家電、車、ロボット、IoT機器など、身の回りのほとんどの電子機器に入っています。',
    relatedTerms: ['GPIO', 'プログラム', 'センサー', 'コンピュータ'],
    lessonNumbers: [3, 44, 45],
  },
  {
    slug: 'gpio',
    term: 'GPIO',
    oneLiner: '汎用入出力ピン',
    explanation: 'GPIO（General Purpose Input/Output）は、マイコンについている多目的のピンです。プログラムで「入力」か「出力」を切り替えられ、センサーをつないだり、LEDを光らせたりできます。',
    example: 'Raspberry Piには40本のGPIOピンがあり、様々な部品をつなげます。',
    useCase: 'センサーの値を読み取ったり、リレーを動かしたり、外の世界とやり取りするために使います。',
    relatedTerms: ['マイコン', '入力', '出力'],
    lessonNumbers: [4, 44, 67],
  },
  {
    slug: 'api',
    term: 'API',
    oneLiner: 'プログラム同士の会話方法',
    explanation: 'API（Application Programming Interface）は、あるプログラムが別のプログラムと情報をやり取りするための決まりごとです。レストランのメニューのように、「これを頼めばこれが返ってくる」というルールです。',
    example: '天気APIを使うと、今日の天気情報をプログラムで取得できます。',
    useCase: 'クラウドサービスと連携したり、他のシステムとデータをやり取りするために使います。',
    relatedTerms: ['クラウド', 'Wi-Fi', 'IoT'],
    lessonNumbers: [55, 56, 57],
  },
  {
    slug: 'wifi',
    term: 'Wi-Fi',
    oneLiner: '無線でネットにつなぐ',
    explanation: 'Wi-Fiは、ケーブルなしでインターネットやネットワークに接続する無線通信技術です。スマートフォンやパソコンと同じように、マイコンもWi-Fiでインターネットに接続できます。',
    example: 'ESP32はWi-Fi内蔵で、センサーデータをインターネット経由で送信できます。',
    useCase: 'IoT機器をインターネットにつなぎ、離れた場所からデータを見たり操作したりするために使います。',
    relatedTerms: ['API', 'クラウド', 'IoT'],
    lessonNumbers: [55, 56],
  },
  {
    slug: 'cloud',
    term: 'クラウド',
    oneLiner: 'インターネット上のコンピュータ',
    explanation: 'クラウドは、インターネット上にあるコンピュータやサービスのことです。自分のパソコンではなく、インターネットの向こう側でデータを保存したり、計算したりできます。',
    example: 'AWS、Google Cloud、Azureなどがクラウドサービスです。',
    useCase: 'センサーデータの保存、AI処理、遠隔監視など、大量のデータや複雑な処理に使います。',
    relatedTerms: ['API', 'Wi-Fi', 'AI'],
    lessonNumbers: [55, 78],
  },
  {
    slug: 'ai',
    term: 'AI',
    oneLiner: '学習して判断するプログラム',
    explanation: 'AI（人工知能）は、データから学習して、判断や予測ができるプログラムです。画像から物体を認識したり、異常を検知したりできます。',
    example: '画像認識AI、音声認識AI、チャットボットなどがあります。',
    useCase: '工場の欠陥検出、顔認証、自動運転など、人間の判断を代わりにする場面で使います。',
    relatedTerms: ['クラウド', 'センサー', 'カメラ'],
    lessonNumbers: [78, 79, 80],
  },
  {
    slug: 'input',
    term: '入力',
    reading: 'にゅうりょく',
    oneLiner: '外から情報を受け取る',
    explanation: '入力は、センサーやボタンなどから情報を受け取ることです。コンピュータにとっての「目」や「耳」にあたります。',
    example: 'ボタンを押す、温度を測る、画像を撮るなどが入力です。',
    useCase: 'システムが外の世界を知り、状況に応じた動作をするために必要です。',
    relatedTerms: ['出力', 'センサー', 'GPIO'],
    lessonNumbers: [4, 5],
  },
  {
    slug: 'output',
    term: '出力',
    reading: 'しゅつりょく',
    oneLiner: '外に向けて動作する',
    explanation: '出力は、LEDを光らせたり、モーターを回したり、画面に表示したりすることです。コンピュータにとっての「手」や「口」にあたります。',
    example: 'LEDを点灯する、スピーカーで音を出す、ディスプレイに文字を表示するなどが出力です。',
    useCase: '処理結果を人間に伝えたり、機械を動かしたりするために必要です。',
    relatedTerms: ['入力', 'GPIO', 'マイコン'],
    lessonNumbers: [4, 19],
  },
  {
    slug: 'circuit',
    term: '回路',
    reading: 'かいろ',
    oneLiner: '電気が流れる道',
    explanation: '回路は、電気が流れるための道すじです。電池、導線、部品がつながって輪になっていると、電流が流れます。輪が切れていると電流は流れません。',
    example: '電池、スイッチ、LEDを導線でつなぐと簡単な回路ができます。',
    useCase: 'あらゆる電子機器の基本です。回路を設計することで、望む動作を実現できます。',
    relatedTerms: ['電圧', '電流', '抵抗', '電池', 'オームの法則'],
    lessonNumbers: [1, 7, 8, 9, 10],
  },
  {
    slug: 'battery',
    term: '電池',
    reading: 'でんち',
    oneLiner: '電気を蓄えて供給する',
    explanation: '電池は、化学反応で電気を作り出す部品です。＋極と−極があり、その間に電圧が生まれます。回路に電気を供給する「電源」の一種です。',
    example: '乾電池（1.5V）、リチウム電池（3.7V）、モバイルバッテリー（5V）などがあります。',
    useCase: 'ポータブル機器の電源として、コンセントがない場所でも電子機器を動かすために使います。',
    relatedTerms: ['電圧', '回路'],
    lessonNumbers: [1, 7],
  },
  {
    slug: 'machine',
    term: '機械',
    reading: 'きかい',
    oneLiner: '力を伝えて仕事をする仕組み',
    explanation: '機械は、モーターやギア、レバーなどを組み合わせて、力を伝えたり変換したりして仕事をする仕組みです。電気が「情報やエネルギーを運ぶ」のに対し、機械は「力を使って物を動かす」役割を担います。',
    example: '自動車のエンジン、エレベーター、ロボットアーム、洗濯機のドラムなどが機械です。',
    useCase: '工場の生産ライン、建設機械、輸送機器など、物理的に何かを動かす場面で使います。',
    relatedTerms: ['モーター', '電気', 'ロボット'],
    lessonNumbers: [2],
  },
  {
    slug: 'computer',
    term: 'コンピュータ',
    oneLiner: '計算と判断をする機械',
    explanation: 'コンピュータは、プログラムに従って計算や判断を行う機械です。入力された情報を処理して、結果を出力します。スマートフォンもパソコンもマイコンも、すべてコンピュータの一種です。',
    example: 'パソコン、スマートフォン、タブレット、ゲーム機、Arduino、Raspberry Piなどがコンピュータです。',
    useCase: 'データ処理、自動制御、通信、表示など、あらゆる「考える」作業に使います。',
    relatedTerms: ['プログラム', 'マイコン', '入力', '出力'],
    lessonNumbers: [3, 44],
  },
  {
    slug: 'program',
    term: 'プログラム',
    reading: 'ぷろぐらむ',
    oneLiner: 'コンピュータへの指示書',
    explanation: 'プログラムは、コンピュータに「何をどの順番でするか」を伝える指示の集まりです。「もし〜なら〜する」「〜を繰り返す」といった命令を並べて書いておくと、コンピュータがその通りに動きます。料理のレシピのように、上から順に実行されます。',
    example: 'スマホアプリ、ウェブサイト、ゲーム、エアコンの温度制御、自動運転システムなど、すべてプログラムで動いています。',
    useCase: 'コンピュータに自動で仕事をさせたいとき、プログラムを書いて指示します。センサーの値を見て「こうなったらこう動く」を決めるのがプログラムの役割です。',
    relatedTerms: ['コンピュータ', 'マイコン', 'AI', '処理'],
    lessonNumbers: [3, 6],
  },
  {
    slug: 'processing',
    term: '処理',
    reading: 'しょり',
    oneLiner: 'コンピュータが行う計算や判断',
    explanation: '処理とは、コンピュータが入力を受け取って行う計算や判断のことです。「入力→処理→出力」の流れの中核で、プログラムに書かれた手順に従って動きます。条件を比べたり、数値を計算したり、データを変換したりすることが処理にあたります。',
    example: '「温度が30度を超えたかチェックする」「数字を足し算する」「文字を表示用に変換する」などが処理です。',
    useCase: 'センサーからの入力を受け取り、出力（LEDを点ける、モーターを回す）を決定する際に使います。',
    relatedTerms: ['入力', '出力', 'プログラム', 'コンピュータ'],
    lessonNumbers: [4, 6],
  },
  {
    slug: 'physical-quantity',
    term: '物理量',
    reading: 'ぶつりりょう',
    oneLiner: '測れる自然の量',
    explanation: '物理量とは、温度・光の強さ・距離・重さ・速度など、自然界で測れる量のことです。センサーは、この物理量を電気信号に変換してコンピュータに伝えます。目に見えない物理量を数値化することで、コンピュータが世界を理解できるようになります。',
    example: '温度（℃）、距離（cm）、明るさ（lux）、重さ（kg）、圧力（Pa）などが物理量です。',
    useCase: 'センサー選びの際に「何の物理量を測りたいか」を明確にし、適切なセンサーを選定します。',
    relatedTerms: ['センサー', '入力', '電気信号'],
    lessonNumbers: [5],
  },
  {
    slug: 'electrical-signal',
    term: '電気信号',
    reading: 'でんきしんごう',
    oneLiner: '情報を運ぶ電気の変化',
    explanation: '電気信号とは、情報を伝えるために電圧や電流を変化させたものです。センサーは物理量を電気信号に変え、コンピュータは電気信号を読み取って処理します。電気信号には、オン・オフだけのデジタル信号と、連続的に変化するアナログ信号があります。',
    example: 'ボタンを押すと「5V」、離すと「0V」という電気信号がマイコンに届きます。',
    useCase: 'センサーとコンピュータの間で情報をやり取りする際に使います。',
    relatedTerms: ['センサー', 'GPIO', 'マイコン', '電圧'],
    lessonNumbers: [5, 7],
  },
  {
    slug: 'ampere',
    term: 'アンペア',
    reading: 'あんぺあ',
    oneLiner: '電流の単位',
    explanation: 'アンペア（A）は、電流の大きさを表す単位です。1アンペアはかなり大きな電流で、電子工作では1000分の1のミリアンペア（mA）をよく使います。名前はフランスの物理学者アンペールに由来します。',
    example: 'LEDには10〜20mA、スマホの充電には1〜2A、エアコンには10A以上の電流が必要です。',
    useCase: '部品に流れる電流の大きさを表すために使います。部品には流せる電流の限界があり、この単位で示されます。',
    relatedTerms: ['電流', '電圧', 'オーム', 'オームの法則'],
    lessonNumbers: [8, 10],
  },
  {
    slug: 'ohm',
    term: 'オーム',
    reading: 'おーむ',
    oneLiner: '抵抗の単位',
    explanation: 'オーム（Ω）は、抵抗の大きさを表す単位です。Ωは「オメガ」というギリシャ文字です。数字が大きいほど電流が流れにくくなります。1000Ωは1キロオーム（1kΩ）と書きます。名前はドイツの物理学者オームに由来します。',
    example: 'LEDに使う抵抗は330Ωや470Ωがよく使われます。センサーの回路には10kΩの抵抗がよく使われます。',
    useCase: '抵抗器を選ぶときに使います。電流を制限するために、適切な値のオームを選びます。',
    relatedTerms: ['抵抗', '電流', 'アンペア', 'オームの法則'],
    lessonNumbers: [9, 10],
  },
  {
    slug: 'ohms-law',
    term: 'オームの法則',
    reading: 'おーむのほうそく',
    oneLiner: '電圧・電流・抵抗の関係式',
    explanation: 'オームの法則は、電圧（V）、電流（I）、抵抗（R）の関係を表す式です。V = I × R（電圧 = 電流 × 抵抗）。電流を求めるときは I = V ÷ R、抵抗を求めるときは R = V ÷ I を使います。回路設計の基本となる法則です。',
    example: '3Vの電池に330Ωの抵抗をつなぐと、I = 3V ÷ 330Ω ≈ 9mA の電流が流れます。',
    useCase: 'LEDにつなぐ抵抗の値を計算したり、回路に流れる電流を予測したりするために使います。回路設計の基本です。',
    relatedTerms: ['電圧', '電流', '抵抗', 'アンペア', 'オーム'],
    lessonNumbers: [1, 10],
  },
]

export function getGlossaryTerm(slug: string): GlossaryTerm | undefined {
  return glossaryTerms.find((t) => t.slug === slug)
}

export function getAllGlossaryTerms(): GlossaryTerm[] {
  return glossaryTerms
}

export function getTermsByLesson(lessonNumber: number): GlossaryTerm[] {
  return glossaryTerms.filter((t) => t.lessonNumbers.includes(lessonNumber))
}
